language: node_js

node_js:
  - 10
  - 9
  - 6

# In order to avoid double build on pull requests, 
# only build on pushes on master and on pushes on pull requests
branches:
  only:
    - master

install:
  # Use npm 5.7.x since it has introduced `npm ci`
  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
  - npm ci

script:
  # Run tests without coverage since it's 2x faster
  - npm run test:jest -- --runInBand

branches:
  only:
    - master

stages:
  - lint
  - test
  - integration

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
        - npx danger ci

    - stage: integration
      script:
        # Compile JS
        - npm run compile
        # Build all examples
        - npm run build:basic
        - npm run build:customised
        - npm run build:sections
        # Check that examples really works: no JS errors on load
        - npm run test:browser:pre
        - npm run test:browser:basic
        - npm run test:browser:customised
        - npm run test:browser:sections
        # Run integration tests with Cypress
        - npm run test:cypress:pre
        - npm run test:cypress:startServer &
        - npm run test:cypress:startServer:post
        - npm run test:cypress:run

    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm install semantic-release
          - npx semantic-release

      # Build & Deploy the documentation website
    - stage: documentation
      script:
        - npm run docs:build
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: docs/dist
        target-branch: master
        repo: vue-styleguidist/vue-styleguidist.github.io
        github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master
          