version: 2

defaults: &defaults
  docker:
    - image: cypress/included:3.4.0
  working_directory: ~/vue-styleguidist

jobs:
  install:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-styleguidist-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v1-vue-styleguidist-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - vue-styleguidist

  compile:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn compile
      - persist_to_workspace:
          root: ~/
          paths:
            - vue-styleguidist

  examples-basic:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      # Build all examples
      - run: yarn build basic
      - run: yarn build customised
      - run: yarn build sections
      - run: yarn build vuex

      # Check that examples really works: no JS errors on load
      - run: yarn test:browser basic
      - run: yarn test:browser customised
      - run: yarn test:browser sections
      - run: yarn test:browser vuex

  examples-vuecli:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      # remake the yarn link to vue-cli-plugin
      - run: yarn install
      - run: yarn build vuecli3
      - run: yarn build vuecli-noplugin
      - run: yarn test:browser vuecli3
      - run: yarn test:browser vuecli-noplugin

  examples-other:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      # Build all examples
      - run: yarn build jsx
      - run: yarn build jsx-examples
      - run: yarn build nuxtjs
      - run: yarn build vuetify

      # Check that examples really works: no JS errors on load
      - run: yarn test:browser jsx
      - run: yarn test:browser jsx-examples
      - run: yarn test:browser nuxtjs
      - run: yarn test:browser vuetify

  cypress:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      # run cypress tests
      - run: yarn cross-env CY_EXAMPLE_FOLDER=basic yarn cy
      - store_artifacts:
          path: /root/vue-styleguidist/test/cypress/screenshots
          destination: cy-screenshots-basic
      - run: yarn cross-env CY_EXAMPLE_FOLDER=jsx-examples yarn cy
      - store_artifacts:
          path: /root/vue-styleguidist/test/cypress/screenshots
          destination: cy-screenshots-jsx-examples

workflows:
  version: 2
  test:
    jobs:
      - install
      - compile:
          requires:
            - install
      - examples-basic:
          requires:
            - compile
      - examples-vuecli:
          requires:
            - compile
      - examples-other:
          requires:
            - compile
      - cypress:
          requires:
            - compile
