# This file contains all examples built in the netlify build process
# Netlify build is limited to 15 min. It cannot build it all.
basic
# customised
# jsx-examples
# vueds

# build examples with docgen and vuepress
# docgen

# build cli examples to make sure they build
# vuecli3-class-pug-ts
# vuecli3-custom
# vuecli3-vuetify-ie
