# This is a basic workflow that is manually triggered

name: Deliver Vue Styleguidist

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deliver:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks out the delivery branch
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
          git status
          git config user.name "Vue Styleguidist Bot"
          git config user.email "${BOT_EMAIL}"
          git fetch origin delivery dev
          git pull
          git switch delivery
          git merge dev --no-edit -m "chore: deliver"
          git push
